#pragma once
#include <raylib.h>

// Registry of EMBEDDED fonts, addressed by name: no file to find at runtime, hence identical
// rendering on every target, WASM included. The atlases are generated by tools/gen_ui_font.cpp,
// through raylib's ExportFontAsCode.
//
// Shared by `graphics` (the current font for text calls) and by `ui` (widget labels), so that an
// atlas is loaded only once.

int engine_font_count();
const char* engine_font_name(int idx);
// Returns -1 for an unknown name, leaving the error message to the caller.
int engine_font_index(const char* name);
// The font is loaded on FIRST use: building its atlas creates a texture, which requires a
// graphics context. Falls back to GetFontDefault() on failure.
Font engine_font(int idx);
// Forgets the fonts WITHOUT unloading them: their textures belong to the previous program's
// context, which is already destroyed. Called when a program starts.
void engine_font_reset();

// Index of the default font, the registry entry named "sans".
int engine_font_default();
