#!/bin/bash
# Naming guard, in TWO directions:
#
#  1. The exposed Ollin API: every function or method name a module exposes (the first argument
#     of map_set(..., make(_static)_builtin)) must be camelCase (functions) or PascalCase
#     (constructors: Color, Quat…) — NEVER snake_case. The meta names (__str, __class__,
#     __name__) are excluded.
#
#  2. The internal C++: the engine's code is snake_case. No camelCase identifier may appear in
#     the CODE (outside strings and comments), with the exception of EXTERNAL identifiers: the
#     raylib and rlgl API (rl*, gl*), emscripten::val methods (isNumber…) and the fields of
#     raylib structs (vaoId, texId, meshMaterial…).
#
# For the convention itself, see CLAUDE.md ("Conventions de nommage").
set -u
here=$(dirname "$0")
root=$(cd "$here/.." && pwd)
cd "$root" || exit 2

bad=0

# 1. The exposed API is camelCase.
names=$(grep -rhoE 'map_set\(Value\(std::string\("[A-Za-z_][A-Za-z0-9_]*"\)\), Value::make_(static_)?builtin' src/modules/*.cpp \
        | grep -oE '"[A-Za-z_][A-Za-z0-9_]*"' | tr -d '"' | sort -u)
for n in $names; do
    case "$n" in
        __*) continue ;;   # meta-methods and internal keys
    esac
    if [[ "$n" == *_* ]]; then
        echo "NAMING: API '$n' contient un '_' — l'API Ollin doit être en camelCase"
        bad=$((bad + 1))
    fi
done

# 2. The internal C++ is snake_case: no camelCase but the external names.
residue=$(python3 - "$root" <<'PY'
import re, sys, os, glob
root = sys.argv[1]

def strip(text):
    # Replaces strings, chars, raw strings and comments with spaces, which preserves the
    # offsets, so that only the real CODE is analysed.
    out = []; i = 0; n = len(text)
    while i < n:
        c = text[i]
        # An EM_ASM(...) block is JavaScript stringified by the macro, not C++, so the whole
        # span is neutralised (balanced brackets, ignoring the comments and strings inside).
        # Otherwise its JS identifiers (getElementById, srcObject…) would be taken for C++
        # camelCase.
        ma = re.match(r'\b(?:MAIN_THREAD_)?EM_ASM\w*\s*\(', text[i:])
        if ma:
            k = i + ma.end() - 1  # the position of the '('
            depth = 0; j = k
            while j < n:
                cj = text[j]
                if cj == '/' and j + 1 < n and text[j + 1] == '/':
                    e = text.find('\n', j); j = n if e < 0 else e; continue
                if cj == '/' and j + 1 < n and text[j + 1] == '*':
                    e = text.find('*/', j + 2); j = n if e < 0 else e + 2; continue
                if cj in '"\'':
                    j += 1
                    while j < n:
                        if text[j] == '\\': j += 2; continue
                        if text[j] == cj: j += 1; break
                        j += 1
                    continue
                if cj == '(': depth += 1
                elif cj == ')':
                    depth -= 1
                    if depth == 0: j += 1; break
                j += 1
            out.append(' ' * (j - i)); i = j; continue
        if c == '/' and i + 1 < n and text[i + 1] == '/':
            j = text.find('\n', i); j = n if j < 0 else j
            out.append(' ' * (j - i)); i = j; continue
        if c == '/' and i + 1 < n and text[i + 1] == '*':
            j = text.find('*/', i + 2); j = n if j < 0 else j + 2
            out.append(' ' * (j - i)); i = j; continue
        m = re.match(r'(?:u8|u|U|L)?R"([^ ()\\\t]*)\(', text[i:])
        if m:
            close = ')' + m.group(1) + '"'
            j = text.find(close, i + m.end()); j = n if j < 0 else j + len(close)
            out.append(' ' * (j - i)); i = j; continue
        if c == '"':
            j = i + 1
            while j < n:
                if text[j] == '\\': j += 2; continue
                if text[j] == '"': j += 1; break
                j += 1
            out.append(' ' * (j - i)); i = j; continue
        if c == "'":
            j = i + 1
            while j < n:
                if text[j] == '\\': j += 2; continue
                if text[j] == "'": j += 1; break
                j += 1
            out.append(' ' * (j - i)); i = j; continue
        out.append(c); i += 1
    return ''.join(out)

# The external names allowed: the emscripten::val API and the fields of raylib structs.
ALLOW = {
    'isNull', 'isNumber', 'isUndefined', 'isString', 'isArray', 'isTrue', 'isFalse',
    'blendMode', 'materialCount', 'meshCount', 'meshMaterial', 'texId',
    'triangleCount', 'vaoId', 'vboId', 'vertexCount', 'boneCount', 'baseSize',
}
def is_ext(t):
    if t in ALLOW: return True
    if t.startswith('rl') and len(t) > 2 and t[2].isupper(): return True   # rlgl
    if t.startswith('gl') and len(t) > 2 and t[2].isupper(): return True   # GL
    return False

files = glob.glob(os.path.join(root, 'src', '**', '*.cpp'), recursive=True) \
      + glob.glob(os.path.join(root, 'src', '**', '*.h'), recursive=True)
# Files GENERATED by an external tool: their identifiers are the tool's, not choices of the
# project, and a correction would be wiped out by the next generation.
GENERATED = {'font_sans.h', 'font_mono.h'}
files = [f for f in files if os.path.basename(f) not in GENERATED]
seen = {}
for f in files:
    code = strip(open(f).read())
    for i, line in enumerate(code.split('\n'), 1):
        for m in re.finditer(r'\b[a-z][a-z0-9]*[A-Z][A-Za-z0-9]*\b', line):
            t = m.group(0)
            if not is_ext(t):
                seen.setdefault(t, (os.path.relpath(f, root), i))
for t, (f, ln) in sorted(seen.items()):
    print(f"{t}\t{f}:{ln}")
PY
)
if [ -n "$residue" ]; then
    while IFS=$'\t' read -r tok loc; do
        echo "NAMING: identifiant interne '$tok' en camelCase ($loc) — le C++ interne doit être en snake_case"
        bad=$((bad + 1))
    done <<< "$residue"
fi

if [ $bad -eq 0 ]; then
    echo "OK   nommage (API camelCase ; C++ interne snake_case)"
    exit 0
fi
echo "$bad nom(s) non conforme(s)"
exit 1
