#pragma once
#include <string>

enum class TokenType {
    NUMBER, STRING, IDENTIFIER,
    VAR, GLOBAL, CONSTANT, WHILE, DO, IF, THEN, END, BREAK, CONTINUE, TRUE, FALSE, NOT,
    TRY, CATCH, THROW, ELSE, ELSEIF, FUNC, RETURN, NIL,
    FOR, IN,
    IMPORT, AS,
    CLASS, EXTENDS,
    SEMICOLON, DOT_DOT_DOT,
    EQUALS, EQUAL_EQUAL, COMMA, LPAREN, RPAREN,
    PLUS, MINUS, STAR, SLASH, PERCENT, SLASH_SLASH, STAR_STAR,
    PLUS_EQUAL, MINUS_EQUAL, STAR_EQUAL, SLASH_EQUAL, PERCENT_EQUAL,
    OR, AND,
    GREATER, LESS, GREATER_EQUAL, LESS_EQUAL, NOT_EQUAL,
    LBRACE, RBRACE, LBRACKET, RBRACKET, COLON, DOT,
    AMP, PIPE, CARET, TILDE, LSHIFT, RSHIFT,
    COMMENT,
    EOF_T
};

struct Token {
    TokenType type;
    std::string lexeme;
    int line;
};
